# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kaggle',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/kaggle',
                'lib_path': 'kaggle'},
  'syms': {'kaggle.core': {'kaggle.core.foo': ('core.html#foo', 'kaggle/core.py')}}}